NumPy - Numerical Python is a high-performance library fr numerical operations. It replaces slow nested python loops with fast, Optimized C-Based operations usings nd-arrays (N-Dimensional Array)


Why choose ndarray over python lists? 
    * Lists are slow, memory ineffecient
    * No vectorized math supported -> ([1, 2, 3] + 10 -> Error in python, but works in NumPy)
    * NumPy uses contiguous Memory Blocks, Making it super fast


Contiguous Memory Blocks:
-------------------------
    This means that all the elements of the array are stored in ajacent memory blocks. 
    -> Data is stored as a homogenous array (Same data type)
    -> All elements are laid out in memory back to back which allows for effecient access and vectorized calculations. 

    Contiguous Memory Block is faster because it makes use of 
        -> CPPU Cache Effeciency
        -> SIMD (Single Instruction, Multiple Data)
        -> Vectoized Instruction
        -> No type checking of every element in the loop (since it a homogenous array)
        -> Effecient memory use


Other Things to rember:
    -> Slicing and some other attributes creates a View, where when we make any changes to the result the original array will be changed
    -> Fancy Indexing creates a copy, wher when we alter the result the original array remains unchanged.


In [ ]:
#Time difference of Python Array and Nupy Array calculation: 

import numpy as np
import time

# Python list square
lst = list(range(10_000_00))
start = time.time()
lst_squared = [x**2 for x in lst]
end = time.time()
print("Python list time:", end - start)

# NumPy array square
arr = np.arange(10_000_00)
start = time.time()
arr_squared = arr**2
end = time.time()
print("NumPy array time:", end - start)


In the above example: 

The generated list with 1000000 elements.
When we try to square the generated 1000000 elements generated in the script.

In Python List: 
-> Each element is a individual python object
-> The interpreter has to repeatedly (fetach_object -> check_type -> do_operations -> store_result)

In NumPy Array:
-> Each element is stored in a continous block of memory
-> The interpreter knows the data_type of the stored objects ahead of time (so it doesn't need to check the time for each element seperately)
-> Uses C-Optimized Loops (SIMD, Vectorized Machine Code)
-> This avoids Python's per-element overhead.


==================Creating Arrays in NumPy========================

There are multiple ways to create a NumPy Array

1. np.array([1, 2, 3])              -> Using a Python list
2. np.arange(start, stop, step)     -> Like range() function in Python
3. np.linspace(start, stop, num)    -> similar to arange in numPy/Range() in Python. But, in arange()/Random() we give the number of step (i.e. the space between two points as step= argument) whereas here we give the number of points that we want in our boundary (start= & stop=)
4. np.zeros(shape)
5. np.full(shape)
6. np.ones(shape)
7. np.random                         -> Random Number arrays

For Example refer the below code block. 

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.arange(0, 10, 2)
c = np.linspace(0, 1, 5)
d = np.zeros((2, 3))
e = np.ones((3, 2))
f = np.full((2, 2), 7)

print("a:", a)
print("b:", b)
print("c:", c)
print("d:\n", d)
print("e:\n", e)
print("f:\n", f)


==================NumPy Array Attributes========================

There are multiple attributes to a numPy Array

Example NumPy Array = arr = [[1, 2, 3], 
                             [4, 5, 6]]

1. arr.shape    -> gives the shape of an array here in this case (2, 3)  | tuple of array dimensions (rows, cols, …).
2. arr.ndim     -> gives the dimension of the array (Number of axes will be the output) in this case 2 
3. arr.dtype    -> returns the datatype of the numpy array (All elements in an array should be same)
4. arr.size     -> return the number of elements present in the array. here in this case (6)
5. arr.itemsize -> self explaining (itemsize in memory)

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Data type:", arr.dtype)
print("Number of elements:", arr.size)
print("Bytes per element:", arr.itemsize)

========================Indexing & Slicing========================
NumPy arrays are n-dimensional grids. Indexing/slicing rules are consistent across 1D, 2D, and higher dimensions.

-> Works like Python lists but extended to higher dimensions. 
-> Syntax = arr[row_index, col_index]
-> Indexing is Zero Based
-> Negative Indexing Works [-1 is last element, -2 is second last element, and so on....]
-> Slices are views (not copies) unless you explicitly .copy()   -> Views = when you alter the result array, the original array will also be affected. 
-> Can be used only for sequential selection

Example of views and Copy (The last statement)
a = np.arange(10)
b = a[2:5]
b[0] = 999
print(a)
# Output will be → [  0   1 999   3   4   5   6   7   8   9]

In [ ]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

# Your task: predict outputs
print("1:", arr[0, 2])    #Should give zeroth row & third column   
print("2:", arr[2, -1])   #Should give third row & first from last column
print("3:\n", arr[1:, 1:3])  # 1: -> rows 1 to end,  1:3 -> columns 1 up to 3
print("4:\n", arr[:2, ::2])  # :2 -> first 2 rows (rows 0 and 1) , ::2 -> every second column (columns 0 and 2)


In [ ]:
arr = np.array([[ 1,  2,  3,  4,  5],
                [ 6,  7,  8,  9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

print("A:\n", arr[1:3, :])  # 1:3 -> rows 1 and 2, : -> all columns
print("B:\n", arr[:, 2:5])  # : -> all columns, 2:5 -> columns 2,3,4
print("C:\n", arr[::2, 1::2]) # ::2 -> every second column (columns 0 and 2), 1::2 -> every second column starting from index 1 → columns 1 and 3

In [ ]:
arr = np.array([[ 1,  2,  3,  4,  5],
                [ 6,  7,  8,  9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]])

print("Q1:\n", arr[-2:, 2:])   #-> [[18 19 20],[23 24 25]]
print("Q2:\n", arr[::-1, 0:2]) #-> [[21 22],[16 17],[11 12],[ 6  7],[ 1  2]]
print("Q3:\n", arr[1:5:2, ::2]) #-> [[ 6  8 10],[16 18 20]]
print("Q4:\n", arr[::2, -3:]) #-> [[ 3  4  5],[13 14 15],[23 24 25]]


========================Boolean Indexing========================

-> Instead of slicing by positions ([1:3]), you filter the array with True/False masks.
-> A boolean mask must have the same shape as the dimension it’s indexing.
-> Wherever the mask is True → element is kept.
-> Flattens results by default unless you combine with slicing.


In [ ]:
arr = np.array([[ 5, 10, 15, 20],
                [25, 30, 35, 40],
                [45, 50, 55, 60],
                [65, 70, 75, 80]])

print(arr[arr > 40])                #-> [45, 50, 55, 60, 65, 70, 75, 80]
print(arr[arr % 20 == 0])           #-> [20, 40, 60, 80]
print(arr[arr[:, 0] > 30])          #-> [45, 50, 55, 60, 65, 70, 75, 80]
print(arr[(arr > 30) & (arr < 70)]) #-> [35, 40, 45, 50, 55, 60, 65]
print(arr[arr[:, 1] > 25, 1])       #-> [30, 50, 70]

========================Boolean Indexing + Slicing (Practice)========================

In [ ]:
arr = np.array([[ 1,  2,  3,  4,  5],
                [ 6,  7,  8,  9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]])

print(arr[-2:, :][arr[-2:, :] > 20])      #-> [21, 22, 23, 24, 25]
print(arr[:3, :][arr[:3, :] % 2 == 0])    #-> [2, 4, 6, 8, 10, 12, 14]
print(arr[arr[:, -1] > 15])               #-> [[16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]
print(arr[(arr > 10) & (arr % 5 == 0)])   #-> [15 20 25]

========================Fancy Indexing========================

Fancy Indesxing is when we use integers/list of integers to pick spcific rows, columns or elements from a NumPy Array - instead of slicing sequentially. 
    -> You can select any combination of indices, not just contiguous ones.
    -> Fancy indexing returns a copy, not a view. Changing the result won’t affect the original array. 
    -> Can be applied to 1D or 2D arrays (or higher dimensions).
    -> You can reorder or skip elements freely — you’re not limited to slices like [start:stop:step].


Example 1:
---------- 
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4] # pick 1st, 3rd, 5th elements

print(arr[indices])

output = [10 30 50]

Example 2:
----------
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr[[0, 2], :])   # pick rows 0 and 2, all columns

Output = [[1 2 3]
          [7 8 9]]

Example 3:
----------
print(arr[[0, 2], [1, 2]]) #Fancy indexing with multiple arrays works elementwise. So we are just saying to pick the (0,2) element and (2,2) element from the array

Output = [2 9]

Example 4:
----------

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Reorder rows
print(arr[[2, 0, 1], :])

Output = [[7 8 9]
          [1 2 3]
          [4 5 6]]

# Reorder columns
print(arr[:, [2, 0, 1]])

Output = [[3 1 2]
          [6 4 5]
          [9 7 8]]


In [ ]:
arr = np.array([[ 1,  2,  3,  4,  5],
                [ 6,  7,  8,  9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]])

print(arr[[0, 2, 4], :])         
print(arr[:, [0, 2, 4]])         
print(arr[[0, 2, 4], [1, 3, 0]])  
print(arr[[4, 3, 0], :])         
print(arr[:, [4, 0, 2]])          


rows = arr[arr[:, 0] > 10]
print(rows[:, [1, 3]])            


========================Brodcasting========================

Broadcasting allows Numpy to perform arthemitic operation on Arrays of different Shapes, Without making explicit copies
-> NumPy automatically streches the smaller array along the dimensions to match the larger array.
-> No Extra memory is used - It's just a logical expansion

RULES OF BRODCASTING:
When operations on two arrays, NumPy compares the shape from trailing dimensions. Two dimensions are compatible if.
1. They are equal, or
2. One of them is 1

If these conditions are not met -> ValueError


Example:
col = np.array([[1],
                [2],
                [3]])
row = np.array([10,20,30])

Here internally NumPy does expand the [10,20,30] array like [[10,20,30],                   [1],                                             [[11,21,31],
                                                             [10,20,30],                   [2],                                              [12,22,32],
                                                             [10,20,30]] this and the adds [3] to each element and the result array will be  [13,23,33]]

========================Brodcasting Examples========================

In [ ]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([10,20,30])
 
print("Q1:\n", A + b) 

In [ ]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
c = np.array([[10],
              [20],
              [30]])
print("Q2:\n", A + c)

In [ ]:
x = np.array([1,2,3])
y = np.array([[10],[20],[30]])
print("Q3:\n", x + y)

In [ ]:
arr = np.array([[1,2,3,4],
                [5,6,7,8]])
v = np.array([1,0,1,0])
print("Q4:\n", arr * v)

In [ ]:
arr = np.array([[10,20,30],
                [40,50,60]])
scale = np.array([2])
print("Q5:\n", arr / scale)

In [ ]:
arr = np.array([[1,2],
                [3,4],
                [5,6]])
bad = np.array([1,2,3])
print("Q6:\n", arr + bad)

========================Universal Functions (ufuncs)========================

-> Universal Functions (ufuncs) are NumPy’s built-in vectorized functions
-> They apply elementwise to arrays, but written in C for speed.
-> No Python loops.

Think of them as the supercharged versions of Python’s math functions.

There are three types of ufuncs
1. Unary ufuncs -> Applied on a single array
    
    a = np.array([1, 2, 3, 4, 5])

    - np.sqrt(a)          # Square root
    - np.exp(a)           # Exponential
    - np.log(a)           # Natural log
    - np.negative(a)      # Negation
    - np.abs()            # Absolute Value

2. Binary unfuncs -> Applid on two array
    
    x = np.array([1, 2, 3])
    y = np.array([10, 20, 30])

    - np.add(x, y)       # [11 22 33]
    - np.subtract(x, y)  # [-9 -18 -27]
    - np.multiply(x, y)  # [10 40 90]
    - np.divide(y, x)    # [10. 10. 10.]
    - np.power(x, 2)     # [1 4 9]

3. Aggregate/Reduction unfuncs -> Operate on entire arrays (or along an axis)

    M = np.array([[1,2,3],
                  [4,5,6]])

    - np.sum(M)         # 21
    - np.sum(M, axis=0) # [5 7 9]   (column-wise sum)
    - np.sum(M, axis=1) # [6 15]    (row-wise sum)
    - np.min(M)         # 1
    - np.max(M)         # 6
    - np.mean(M)        # 3.5
    - np.std(M)         # Standard deviation


Real-world use cases
    -> Normalization of datasets
    -> Statistical summaries (mean, std, min, max)
    -> Applying math transformations (log, exp, sqrt) in ML pipelines
    -> Elementwise transformations in image/audio data

========================Shape Manipulation========================

What does reshaping do: Changes the shape of an array without changing its data
Rule: The number of elements remain the same.

Different Attributes:
1. arr.reshape(rows, cols, additional if in case want to convert to 3d array)  => Ideally coverts 1D to 2D/3D
2. arr.flatten() -> takes multi dimensional array and converts them to 1D array
3. arr.ravel() -> same as flatten() but returns a view instead of copy. 
4. arr.transpose(axes) / arr.T -> Transpose of a matrix
5. numPy.newaxis -> to add a new axis(row/col)                                          ***************#########Have to study this part again#########***************
6. numPy.expand_dims -> same functionality as 'nexaxis' but syntax is different
7. numPy.squeeze -> Removes size-1 dimensions
8. Stacking
    - hstack -> stack horizontally
    - vstack -> stack vertically
    - concatenate -> generic version
9. Splitting Arrays
    - split -> split into equal-sized chunks
    - hsplit -> split horizontally
    - vsplit -> split vertically



In [ ]:
input_arr = np.arange(12)
input_arr

#Reshape array
reshaped_arr = input_arr.reshape(3, 4).copy() # use .copy() inplace where you don't want the changes to the result array to affect the original array
print(f"Reshaoed Array: {reshaped_arr} \n")

flattened_arr = reshaped_arr.flatten().copy()
print(f"Flattened Array: {flattened_arr} \n")

transd_arr = flattened_arr.reshape(3, 4).T.copy()
print(f"Transposed Array: {transd_arr} \n")



Reshaoed Array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11] 

Transposed Array: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
